# .travis.yml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

language: cpp
compiler: gcc
dist: xenial

cache:
  directories:
  - $HOME/.cache

env:
  global:
    - SETUP_PATH=.ci-local:.ci
    - BASE=SELF
    - EPICS_TEST_IMPRECISE_TIMING=YES

addons:
  apt:
    packages:
    # for all EPICS builds
    - libreadline6-dev
    - libncurses5-dev
    - perl
    # for clang compiler
    - clang
    # for mingw builds (32bit and 64bit)
    - g++-mingw-w64-i686
    - g++-mingw-w64-x86-64
    # for RTEMS cross builds
    - qemu-system-x86
  homebrew:
    packages:
    # for all EPICS builds
    - bash
    update: true

install:
  - ./.ci-local/travis-fixup.sh
  - python .ci/cue.py prepare

script:
  - python .ci/cue.py build
  - python .ci/cue.py test
  - python .ci/cue.py test-results

# Define build jobs

jobs:
  include:

# Different configurations of default gcc and clang
  - dist: bionic

  - dist: xenial

  - dist: bionic
    env: BCFG=static EXTRA="CMD_CXXFLAGS=-std=c++11"

  - dist: trusty
    env: EXTRA="CMD_CXXFLAGS=-std=c++11"

  - dist: bionic
    compiler: clang

  - compiler: clang

  - dist: trusty
    compiler: clang
    env: BCFG=static

# Cross-compilations to Windows using MinGW and WINE

  - env: WINE=32 TEST=NO BCFG=static

  - env: WINE=32 TEST=NO

# Cross-compilation to RTEMS

  - env: RTEMS=4.10

  - env: RTEMS=4.9

# MacOS build

  - os: osx
    env:
      - EXTRA="CMD_CFLAGS=-mmacosx-version-min=10.7"
      - EXTRA1="CMD_CXXFLAGS=-mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++"
      - EXTRA2="CMD_LDXFLAGS=-mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++"
    compiler: clang
